#!/bin/bash

# PWA Icon Generator Script
# This script helps you understand what icon files you need for your PWA

echo "🎨 PWA Icon Requirements for Focus Pomodoro App"
echo "================================================"
echo ""
echo "You need to create the following icon files:"
echo ""
echo "📱 Standard Icons:"
echo "  - favicon.ico (16x16, 32x32, 48x48 multi-size)"
echo "  - favicon-16x16.png"
echo "  - favicon-32x32.png"
echo "  - icon-72x72.png"
echo "  - icon-96x96.png"
echo "  - icon-128x128.png"
echo "  - icon-144x144.png"
echo "  - icon-152x152.png"
echo "  - icon-192x192.png"
echo "  - icon-384x384.png"
echo "  - icon-512x512.png"
echo ""
echo "🍎 Apple-specific:"
echo "  - apple-touch-icon.png (180x180)"
echo ""
echo "🪟 Microsoft-specific:"
echo "  - ms-icon-144x144.png"
echo ""
echo "💡 Recommended Tools:"
echo "  • PWA Builder (https://www.pwabuilder.com/imageGenerator)"
echo "  • Favicon.io (https://favicon.io/)"
echo "  • RealFaviconGenerator (https://realfavicongenerator.net/)"
echo ""
echo "🎯 Design Tips:"
echo "  • Use a simple, recognizable design (timer/tomato theme)"
echo "  • Ensure good contrast for both light and dark backgrounds"
echo "  • Test visibility at small sizes (16x16, 32x32)"
echo "  • Use your brand colors: primary #4f46e5, background #ffffff"
echo ""
echo "📝 Next Steps:"
echo "  1. Create a base design (preferably 512x512 or larger)"
echo "  2. Use online tools to generate all required sizes"
echo "  3. Place all generated files in your project root"
echo "  4. Test your PWA installation"
